{ "*.{json,md,yml,css,js,ts}": ["eslint --fix", "prettier --write"] }
# // module.exports = {
# //   '*.{json,md,yml,css,js,ts}': filenames =>
# //     filenames.map(filename => {
# //       return [
# //         `eslint --fix ${filename}`,
# //         `prettier --write ${filename}`
# //       ]
# //     })
# // }
